# Generated by Django 5.2.8 on 2025-11-09 07:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address to block', unique=True)),
                ('reason', models.TextField(blank=True, help_text='Why this IP was blocked')),
                ('blocked_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this IP was blocked')),
            ],
            options={
                'verbose_name': 'Blocked IP',
                'verbose_name_plural': 'Blocked IPs',
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the client making the request')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the request was made')),
                ('path', models.CharField(help_text='The URL path that was requested', max_length=500)),
                ('country', models.CharField(blank=True, help_text='Two-letter country code (e.g., US, GB, FR)', max_length=2, null=True)),
                ('city', models.CharField(blank=True, help_text='City name from geolocation', max_length=100, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address', 'timestamp'], name='ip_tracking_ip_addr_d89fd9_idx')],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address flagged as suspicious')),
                ('reason', models.TextField(help_text='Why this IP was flagged (e.g., too many requests, accessing sensitive paths)')),
                ('flagged_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this IP was flagged')),
                ('request_count', models.IntegerField(default=0, help_text='Number of requests made in the detection window')),
            ],
            options={
                'ordering': ['-flagged_at'],
                'indexes': [models.Index(fields=['ip_address', 'flagged_at'], name='ip_tracking_ip_addr_dc45bd_idx')],
            },
        ),
    ]
